### ISSUE TITLE
[Sub-Task] useInput 커스텀 훅 개발

### ISSUE THREAD

**Issue by humonnom** [humonnom/ruth-form#6]
- [ ] 총 예상소요시간
- [ ] 총 실제소요시간

- [ ] JS를 TS로 변경(`any`로 해놓고 하나씩 바꾸기)
- [ ] `useInput` 리팩토링
   - [ ] 리팩토링 목적: useInput이 하는 일이 너무 많음, 복잡함
      - [ ] 분리 계획 세우기(30분 => ) 
      - [ ] validation 분리(30분 => )
      - [ ] state 관리도 같이 분리(30분 => )
      - [ ] 디바운스 적용(30분 => )
